### PR TITLE
Fix other options are forbidden when --no-source-map

### LINKED ISSUE #58: Unable to disable source maps
Hey everybody,

I'm trying to disable the output of the link to a source map URL - I don't want to have a source map comment in my generated CSS file. My first thought was: this is easy, just set inside sass_options node `source_map: false` - didn't work. Ok, just set `embed_source_map: false`  - didn't work.

`Command: '/var/www/html/var/dart-sass/sass' '/var/www/html/assets/website/styles/main.scss:/var/www/html/var/sass/main.output.css' '--style=expanded' '--no-source-map' '--no-embed-source-map'`

`--embed-source-map isn't allowed with --no-source-map.`

So, it seems that the combination of these options is not allowed - can you guys help me out and tell me how to disable it.

Thank you in advance!

### PR DESCRIPTION
**Pull request by smnandre**
Fixes #58 

Related Dart source code: https://github.com/sass/dart-sass/blob/006baa5642e6c0ff8bb41da8f914359e06fc04d4/lib/src/executable/options.dart#L440

### CODE REVIEW

**Review by bocharsky-bw — COMMENTED** [review]
OK, this looks good to me technically.

But won't it cause problems when users will see those options in the bundle's configuration but they will be silently ignored? I mean, won't it be better to let the Sass binary throw an error so you could adjust bundle's config instead?

I laterally mean doing something like this in config:
```yaml
symfonycasts_sass:
    sass_options:
        source_map: false
        embed_sources: false
        embed_source_map: false
```

This config should solve the problem, right?

**Comment by bocharsky-bw** [comment]
Lol, ok, now I see myself. The problem is that you get that `--embed-sources isn't allowed with --no-source-map` error no matter if you pass `--embed-sources` or `--no-embed-sources`... which is weird, I would suppose `--no-embed-sources` works because the error message clearly says about `--embed-sources` only 🤦‍♂️ 

So, IMO their (Sass) check isn't ideal as it should allow `--no-embed-sources` with `--no-source-map`... because why not? And if it allowed - we would not need this fix.

Anyway, how about mentioning this in the docs then? :) probably a comment over the `source_map` option is enough. I suppose we should say something like:
> If `source_map` is false - `embed_sources` and `embed_source_map` options are ignored

**Comment by smnandre** [comment]
I wanted to suggest a change on their side... but it's implemented in that way since .... a long time.

This is a quick fix.

What i'd like to do next is use the "enable" symfony config option.


So you'd have something like this


```yaml

symfonycasts_sass:
    sass_options:
    
        # Nothing 
        source-map: false

        # Source map ON  (no embed source)
        source-map: true

        # Source map ON and embed source
        source-map: 
            embed-sources: true
            
        # Source map OFF (and nothing else)
        source-map: 
            enabled: false
            embed-sources: false            
            
        # etc etc    
```            


But really i'd release this fix now as it forbid people to compile their sass file in PROD env :(

**Comment by bocharsky-bw** [comment]
> I wanted to suggest a change on their side... but it's implemented in that way since .... a long time.

Yeah, not a big deal to just work it around I think 👍 

Thank you for this quick fix!

> What i'd like to do next is use the "[enable](https://symfony.com/doc/current/components/config/definition.html#optional-sections)" symfony config option.

That sounds like an interesting idea that would make things clearer... but it would also lead to a BC break in the configuration, though we could probably overcome it with some code complications.

**Pull request merged**
