### PR TITLE
Allow string in 'root_sass' configuration

### PR DESCRIPTION
**Pull request by smnandre**
Allow both string and array to configure `root_sass`. (follows discussion [here](https://github.com/SymfonyCasts/sass-bundle/pull/52#issuecomment-1874368015)

```yaml
symfony_cast:
    root_sass: '%kernel.project_dir%/assets/scss/app.scss'
```

```yaml
symfony_cast:
    root_sass: 
        - '%kernel.project_dir%/assets/scss/app.scss'
```    

Magic done in the dependency extension, so it does not impact any domain code

### CODE REVIEW

**Comment by smnandre** [comment]
Update: still think the documentation / recipes should contains the array version, as it's easier to understand that multiple values are allowed, and how to add them :)

**Review by bocharsky-bw — APPROVED** [review]
Easy win, thanks!

> still think the documentation / recipes should contains the array version, as it's easier to understand that multiple values are allowed, and how to add them

Why not use both? :) I think we can show "string" example first (as it will fit most users), but below mention you can specify more values with an array. Wdyt?

**Comment by smnandre** [comment]
Of course, even better :) 

Just anticipated issues/requests "how can i use multiple pathes" elsewhen :)

**Comment by makraz** [comment]
> Easy win, thanks!
> 
> > still think the documentation / recipes should contains the array version, as it's easier to understand that multiple values are allowed, and how to add them
> 
> Why not use both? :) I think we can show "string" example first (as it will fit most users), but below mention you can specify more values with an array. Wdyt?

@smnandre, I update my PR #52 to update the docs with the array version :)

**Comment by bocharsky-bw** [comment]
Thank you!

**Comment by smnandre** [comment]
I just discover this could be written in a cleaner / shorter way:

```
->beforeNormalization()->castToArray()->end()
```

CF: https://symfony.com/doc/current/components/config/definition.html#array-nodes 

Should i update the code ?

**Comment by makraz** [comment]
> I just discover this could be written in a cleaner / shorter way:
> 
> ```
> ->beforeNormalization()->castToArray()->end()
> ```
> 
> CF: https://symfony.com/doc/current/components/config/definition.html#array-nodes
> 
> Should i update the code ?

@smnandre I can do it you don't mind?

**Comment by smnandre** [comment]
Of course you can :)

**Comment by makraz** [comment]
> I just discover this could be written in a cleaner / shorter way:
> 
> ```
> ->beforeNormalization()->castToArray()->end()
> ```
> 
> CF: https://symfony.com/doc/current/components/config/definition.html#array-nodes
> 
> Should i update the code ?

the PR is here: #55 

cc: @smnandre @bocharsky-bw

**Pull request merged**
