### PR TITLE
fix #75: detect `sass` binary in the path and use it if available

### LINKED ISSUE #75: Proposal to improve SASS binary handling
Hello,

Today, I attempted to build a new instance of the Symfony demo on NixOS, and you can find the log here: https://gist.github.com/drupol/31f96f358e9d35e1095f0ba5dd92c056.

> Downloading and attempting to run a binary on NixOS will almost never work. This is due to hard-coded paths in the executable.
(source: https://wiki.nixos.org/wiki/Packaging/Binaries)

### Why fixing this matters:

1. To improve hermetic builds: by addressing this issue, we can enhance the isolation of builds for Symfony applications using this bundle. Since the builds should run in a fully isolated environment (**no network access**), we need a way to provide the SASS binary as a pre-requisite and avoid the build system downloading it.
2. dependency clarity: this will also ensure we know exactly which dependencies the build system requires upfront, making the build process more predictable and maintainable.
3. offline builds: making sure that "offline" builds of a Symfony app using this bundle will work

### Proposed fix

To address this, I suggest modifying the behaviour of `SassBuilder`. Instead of downloading the SASS binary at build-time, it should first check if the binary is already available in the current system's path. If it finds the binary, it should use that, and only download the file if it is not found.

The current flow looks like this:

```mermaid
flowchart TD
    A[Find SASS Binary]
    A --> E[Download the file using the existing procedure]
```

I propose updating it to the following:

```mermaid
flowchart TD
    A[Find SASS Binary]
    A --> C{Is the SASS binary available in the system path?}
    C -->|Yes| D[Return the path to the binary]
    C -->|No| E[Download the file using the existing procedure]
```

This change would prevent unnecessary downloads and make the build process smoother on systems like NixOS and Guix.

Let me know what you think of the idea.

### PR DESCRIPTION
**Pull request by drupol**
This PR fix #75 by doing:

- Use the binary `sass` if it is available in the path
- If the path is not available in the path, it will try to download it

### CODE REVIEW

**Review by bocharsky-bw — COMMENTED** [review]
Hm, correct me if I'm wrong but you're trying to prioritize the binary from paths among other available binaries. I see this bundle allows to specify the path to the binary you want to use, so it already works the way you need, i.e. you can just specify the path to the local binary from path and it will work for you, right? The only problem with this behaviour is that you need to specify that path manually. In case we want to automate it - we need to follow the next logic IMO:
1. Check if the binary path is set in the config, i.e. `symfonycasts_sass.binary` option. if it's set - just use it, no need to find anything because it's explicitly configured
2. If no `symfonycasts_sass.binary` option is set - try to find the installed binary from the path as you suggest. If found - use it.
3. If no installed binary in the path - try to download the latest binary.

**Comment by drupol** [comment]
OK will adjust my PR then ! Thank you for the review!

**Comment by drupol** [comment]
@bocharsky-bw Ready for another review.

**Review by bocharsky-bw — APPROVED** [review]
This looks good to me know, thanks for this idea!

**Pull request merged**
